---
k3s_version: v1.30.8+k3s1
k3s_server_group: k3s_server
k3s_agent_group: k3s_agents
k3s_tls_san: "{{ hostvars[groups[k3s_server_group][0]].k3s_node_ip | default(hostvars[groups[k3s_server_group][0]].ansible_host) }}"
k3s_server_url: "https://{{ k3s_tls_san }}:6443"

kubeconfig_local_path: "{{ lookup('env', 'KUBECONFIG') | default((lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE'), true)) + '/.kube/sunboys-k3s.yaml', true) }}"

cluster_namespaces:
  - app
  - infra
  - monitoring
